# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/form_FaceRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(50, 50, 381, 351))
        self.labelCamera.setText("")
        self.labelCamera.setScaledContents(True)
        self.labelCamera.setObjectName("labelCamera")
        self.btnAddPerson = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddPerson.setGeometry(QtCore.QRect(650, 380, 91, 23))
        self.btnAddPerson.setObjectName("btnAddPerson")
        self.txt_name_person = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name_person.setGeometry(QtCore.QRect(530, 230, 321, 31))
        self.txt_name_person.setObjectName("txt_name_person")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 210, 101, 16))
        self.label.setObjectName("label")
        self.labelPicturePerson = QtWidgets.QLabel(self.centralwidget)
        self.labelPicturePerson.setGeometry(QtCore.QRect(580, 30, 221, 141))
        self.labelPicturePerson.setText("")
        self.labelPicturePerson.setScaledContents(True)
        self.labelPicturePerson.setObjectName("labelPicturePerson")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 290, 101, 16))
        self.label_2.setObjectName("label_2")
        self.txt_id_person = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_id_person.setGeometry(QtCore.QRect(530, 310, 321, 31))
        self.txt_id_person.setObjectName("txt_id_person")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddPerson.setText(_translate("MainWindow", "Thêm người"))
        self.label.setText(_translate("MainWindow", "Tên người nhận diện:"))
        self.label_2.setText(_translate("MainWindow", "ID người nhận diện:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
